defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/openjdk:8-jdk
  environment:
    MAVEN_OPTS: -Xmx3200m

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: mvn clean install
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build_and_tests:
    jobs: build
